// <auto-generated />
using System;
using Financial.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Financial.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220323014535_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Financial.Domain.Entities.FinanceAccounts.FinanceAccountsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("FinanceAccounts");
                });

            modelBuilder.Entity("Financial.Domain.Entities.FinanceAccounts.FinanceAccountsItemsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Addition")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FinanceAccountId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("GrossTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.HasIndex("FinanceAccountId");

                    b.ToTable("FinanceAccountsItems");
                });

            modelBuilder.Entity("Financial.Domain.Entities.FinanceAccounts.FinanceAccountsPaymentItemsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FinanceAccountsItemsId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Payday")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FinanceAccountsItemsId");

                    b.ToTable("FinanceAccountsPaymentItems");
                });

            modelBuilder.Entity("Financial.Domain.Entities.PaymentTerms.PaymentTermsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ForceExpiration")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PaymentTerms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee811013-f73a-4ebd-b1c0-e63d0b9eeb24"),
                            CompanyId = new Guid("aa889dfd-e85c-4e0d-90cd-34e462afa4f1"),
                            CreateAt = new DateTime(2022, 3, 22, 22, 45, 34, 551, DateTimeKind.Local).AddTicks(935),
                            Description = "Á vista",
                            ForceExpiration = 0,
                            UpdateAt = new DateTime(2022, 3, 22, 22, 45, 34, 552, DateTimeKind.Local).AddTicks(5554)
                        },
                        new
                        {
                            Id = new Guid("39b595a5-f64e-4b2a-9775-f2ecb80d7ecd"),
                            CompanyId = new Guid("aa889dfd-e85c-4e0d-90cd-34e462afa4f1"),
                            CreateAt = new DateTime(2022, 3, 22, 22, 45, 34, 553, DateTimeKind.Local).AddTicks(4974),
                            Description = "30 dias",
                            ForceExpiration = 0,
                            UpdateAt = new DateTime(2022, 3, 22, 22, 45, 34, 553, DateTimeKind.Local).AddTicks(4981)
                        });
                });

            modelBuilder.Entity("Financial.Domain.Entities.PaymentTerms.PaymentTermsItemsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Addition")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Days")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("PaymentTermsId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentTermsId");

                    b.ToTable("PaymentTermsItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90eb60cc-c92a-4c7b-b82b-6aa3a19e419d"),
                            Addition = 0m,
                            CompanyId = new Guid("aa889dfd-e85c-4e0d-90cd-34e462afa4f1"),
                            CreateAt = new DateTime(2022, 3, 22, 22, 45, 34, 553, DateTimeKind.Local).AddTicks(5421),
                            Days = 30,
                            Discount = 0m,
                            PaymentTermsId = new Guid("39b595a5-f64e-4b2a-9775-f2ecb80d7ecd"),
                            UpdateAt = new DateTime(2022, 3, 22, 22, 45, 34, 553, DateTimeKind.Local).AddTicks(5425)
                        });
                });

            modelBuilder.Entity("Financial.Domain.Entities.FinanceAccounts.FinanceAccountsItemsEntity", b =>
                {
                    b.HasOne("Financial.Domain.Entities.FinanceAccounts.FinanceAccountsEntity", "FinanceAccount")
                        .WithMany()
                        .HasForeignKey("FinanceAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinanceAccount");
                });

            modelBuilder.Entity("Financial.Domain.Entities.FinanceAccounts.FinanceAccountsPaymentItemsEntity", b =>
                {
                    b.HasOne("Financial.Domain.Entities.FinanceAccounts.FinanceAccountsItemsEntity", "FinanceAccountsItems")
                        .WithMany("PaymentItems")
                        .HasForeignKey("FinanceAccountsItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinanceAccountsItems");
                });

            modelBuilder.Entity("Financial.Domain.Entities.PaymentTerms.PaymentTermsItemsEntity", b =>
                {
                    b.HasOne("Financial.Domain.Entities.PaymentTerms.PaymentTermsEntity", "PaymentTerms")
                        .WithMany("PaymentTermsItems")
                        .HasForeignKey("PaymentTermsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentTerms");
                });

            modelBuilder.Entity("Financial.Domain.Entities.FinanceAccounts.FinanceAccountsItemsEntity", b =>
                {
                    b.Navigation("PaymentItems");
                });

            modelBuilder.Entity("Financial.Domain.Entities.PaymentTerms.PaymentTermsEntity", b =>
                {
                    b.Navigation("PaymentTermsItems");
                });
#pragma warning restore 612, 618
        }
    }
}
